import { describe, expect, it } from 'vitest';
import {
  buildLlmBoundaries,
  buildEventsFromBoundaries,
  splitContentEventsIntoTurns,
} from '../../../assets/hooks/qoder-hook-processor.mjs';

// Qoder CLI writes slash-command plumbing as type=user rows. Only the caveat and
// the stdout row carry isMeta; the command echo itself does not, so it used to
// start a bogus turn that produced an LLM-less trace skeleton.
function userRow(text, extra = {}) {
  return {
    type: 'user',
    userType: 'external',
    entrypoint: 'cli',
    timestamp: '2026-08-27T06:50:52.808Z',
    message: { role: 'user', content: text },
    ...extra,
  };
}

const caveatRow = () => userRow(
  '<local-command-caveat>Caveat: The messages below were generated by the user '
  + 'while running local commands. DO NOT respond to these messages or otherwise '
  + 'consider them in your response unless the user explicitly asks you to.'
  + '</local-command-caveat>',
  { isMeta: true },
);
const commandRow = () => userRow('<command-message>model</command-message>\n<command-name>/model</command-name>');
const stdoutRow = () => userRow('<local-command-stdout>Model set to Ultimate (persisted)</local-command-stdout>', { isMeta: true });

const promptRow = (text, ts = '2026-08-27T06:50:56.000Z') => userRow(text, {
  promptId: '21c3d055-6800-48b0-a892-c40386abc77c',
  timestamp: ts,
});

function assistantRow(text, ts = '2026-08-27T06:50:57.000Z') {
  return {
    type: 'assistant',
    timestamp: ts,
    message: {
      role: 'assistant',
      model: 'auto',
      stop_reason: 'end_turn',
      content: [{ type: 'text', text }],
    },
  };
}

function toolResultRow(toolUseId, ts = '2026-08-27T06:50:58.000Z') {
  return userRow([{ type: 'tool_result', tool_use_id: toolUseId, content: 'ok' }], { timestamp: ts });
}

const progress = [
  { hookEvent: 'UserPromptSubmit', ts: '2026-08-27T06:50:56.000Z' },
  { hookEvent: 'Stop', ts: '2026-08-27T06:51:00.000Z' },
];

function partsOf(record) {
  return (record?.['gen_ai.input.messages_delta']?.[0]?.parts || []).map(p => String(p.content ?? ''));
}

describe('qoder slash-command control rows', () => {
  it('drops the whole /model control trio instead of opening a turn for it', () => {
    const prompt = promptRow('杭州天气');
    const assistant = assistantRow('杭州今天多云。');
    const turns = splitContentEventsIntoTurns([
      caveatRow(), commandRow(), stdoutRow(), prompt, assistant,
    ]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt, assistant]);
  });

  it('keeps control text out of a preceding real turn input', () => {
    const prompt = promptRow('您好');
    const assistant = assistantRow('您好！我是 Qoder。');
    // The caveat row trails the finished turn, so it used to be appended to it.
    const turns = splitContentEventsIntoTurns([prompt, assistant, caveatRow()]);

    expect(turns).toHaveLength(1);
    const records = buildEventsFromBoundaries(
      buildLlmBoundaries(progress, turns[0]),
      turns[0],
      turns[0],
      'turn-no-leak',
      'session-1',
      'qoder',
      {},
      '/tmp/cwd',
    );

    const entry = records.find(r => r['event.name'] === 'other');
    const request = records.find(r => r['event.name'] === 'llm.request');
    expect(partsOf(entry)).toEqual(['您好']);
    expect(partsOf(request)).toEqual(['您好']);
    for (const record of records) {
      for (const part of partsOf(record)) {
        expect(part).not.toContain('local-command-caveat');
      }
    }
  });

  it('emits no records at all when a segment holds only control rows', () => {
    const turns = splitContentEventsIntoTurns([caveatRow(), commandRow(), stdoutRow()]);
    expect(turns).toEqual([]);
  });

  it('keeps an isMeta image marker on its prompt', () => {
    // Multimodal collection relies on these rows; only command envelopes go away.
    const prompt = promptRow('看这张图');
    const imageMeta = userRow([{ type: 'text', text: '[Image: source: /tmp/clip.png]' }], { isMeta: true });
    const assistant = assistantRow('图里是一只猫。');
    const turns = splitContentEventsIntoTurns([prompt, imageMeta, assistant]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toContain(imageMeta);
  });

  it('still yields one turn for a real prompt that got no model activity', () => {
    // Interrupted turns carry no assistant row and must survive the filter.
    const prompt = promptRow('帮我改一下');
    const turns = splitContentEventsIntoTurns([prompt]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt]);
  });

  it('leaves tool_result rows attached to their prompt', () => {
    const prompt = promptRow('跑一下测试');
    const assistant = assistantRow('我来跑测试。');
    const result = toolResultRow('toolu_1');
    const turns = splitContentEventsIntoTurns([prompt, assistant, result]);

    expect(turns).toHaveLength(1);
    expect(turns[0]).toEqual([prompt, assistant, result]);
  });

  it('keeps a real prompt that starts with control-like XML', () => {
    const prompt = promptRow(
      '<command-name>model</command-name> 这段标签是什么意思？',
    );

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  // Same shape without a promptId, which is the common case: the CLI stamps one
  // on only a small minority of prompts, so the envelope check has to carry this
  // on its own.
  it('keeps a promptId-less prompt that starts with control-like XML', () => {
    const prompt = userRow(
      '<command-name>model</command-name> 这段标签是什么意思？',
    );

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a prompt that wraps a complete envelope in its own words', () => {
    const prompt = userRow(
      '为什么 transcript 里会出现 <local-command-stdout>Model set to Ultimate'
      + '</local-command-stdout> 这种行？',
    );

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a prompt whose control tag is never closed', () => {
    // A dangling opener is prose, not plumbing: the CLI always closes its tags.
    const prompt = userRow('这个 <command-message> 标签要怎么闭合？');

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a prompt whose closing tag does not match its opener', () => {
    const prompt = userRow('<command-message>model</command-name>');

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a prompt that is exactly one command-name envelope', () => {
    // Nothing stops a user from sending this, and the CLI never emits
    // <command-name> on its own — it always pairs it with <command-message>.
    const prompt = userRow('<command-name>model</command-name>');

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a row whose first content block is an envelope but which carries more', () => {
    // Control rows are always a plain string, so a block array is a real message
    // no matter what its first block holds.
    const prompt = userRow([
      { type: 'text', text: '<local-command-stdout>Model set to Ultimate</local-command-stdout>' },
      { type: 'text', text: '这行是从哪来的？' },
    ], { isMeta: true });

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('keeps a control-shaped row that did not come from the CLI', () => {
    const prompt = userRow(
      '<local-command-stdout>Model set to Ultimate</local-command-stdout>',
      { isMeta: true, entrypoint: undefined },
    );

    expect(splitContentEventsIntoTurns([prompt])).toEqual([[prompt]]);
  });

  it('classifies adjacent envelopes with a trailing suffix without stalling', () => {
    // A regex repeating a lazily-matched envelope backtracks exponentially here:
    // 28 envelopes took ~3.8 s locally, and the Stop hook runs the processor in
    // the foreground with no timeout, so this has to stay linear.
    const prompt = userRow(
      '<command-name>x</command-name>'.repeat(40) + '这些标签是什么？',
    );

    const started = performance.now();
    const turns = splitContentEventsIntoTurns([prompt]);
    const elapsed = performance.now() - started;

    expect(turns).toEqual([[prompt]]);
    expect(elapsed).toBeLessThan(200);
  });

  it('keeps a mid-turn control trio out of the merged CLI input parts', () => {
    // For qoder-cli, buildUserMessageParts folds every non-tool-result user row of
    // the turn into the prompt's parts, so a control row surviving the split would
    // resurface as user input on both the turn entry and the first llm.request.
    const prompt = promptRow('杭州天气');
    const assistant = assistantRow('杭州今天多云。');
    const turns = splitContentEventsIntoTurns([
      prompt, caveatRow(), commandRow(), stdoutRow(), assistant,
    ]);

    expect(turns).toHaveLength(1);
    const records = buildEventsFromBoundaries(
      buildLlmBoundaries(progress, turns[0]),
      turns[0],
      turns[0],
      'turn-parts',
      'session-1',
      'qoder',
      {},
      '/tmp/cwd',
    );

    expect(records.find(r => r['event.name'] === 'other')['gen_ai.agent.type']).toBe('qoder-cli');
    expect(partsOf(records.find(r => r['event.name'] === 'other'))).toEqual(['杭州天气']);
    expect(partsOf(records.find(r => r['event.name'] === 'llm.request'))).toEqual(['杭州天气']);
  });

  it('applies the shared CLI control-row filtering to QoderCN SDK transcripts', () => {
    const prompt = promptRow('杭州天气');
    const assistant = assistantRow('杭州今天多云。');
    const turns = splitContentEventsIntoTurns([
      caveatRow(), commandRow(), stdoutRow(), prompt, assistant,
    ]);

    expect(turns).toHaveLength(1);
    const records = buildEventsFromBoundaries(
      buildLlmBoundaries(progress, turns[0]),
      turns[0],
      turns[0],
      'turn-qoder-cn-sdk',
      'session-qoder-cn-sdk',
      'qoder-cn',
      {},
      '/tmp/cwd',
    );

    expect(records.every(r => r['gen_ai.agent.type'] === 'qoder-cn')).toBe(true);
    for (const record of records) {
      for (const part of partsOf(record)) {
        expect(part).not.toMatch(/command-message|command-name|local-command/u);
      }
    }
  });
});
